name: jascare
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.11.3
  image_picker: ^1.1.2
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  flutter_svg: ^2.0.9
  

  cupertino_icons: ^1.0.8
  geolocator: ^14.0.3
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/

